# Bootstrapping argocd server deployment
applications:
  - name: argocd
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: default
    revisionHistoryLimit: 3
    sources:
      - repoURL: 'https://argoproj.github.io/argo-helm'
        targetRevision: 8.2.2
        helm:
          releaseName: argocd
          valueFiles:
            - $values/charts/argocd/argocd-server/staging-argocd-values.yaml
      - repoURL: "git@github.com:/basebandit/zeus.git"
        targetRevision: HEAD
        ref: values
      # Argocd Configuration
      - repoURL: "git@github.com:basebandit/zeus.git"
        path: charts/argocd/argocd-server/argocd-config/staging
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        allowEmpty: true
        prune: true
        selfHeal: true
      syncOptions:
      - allowEmpty=true