apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-orders
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: orders=060309844053.dkr.ecr.eu-central-1.amazonaws.com/orders
    argocd-image-updater.argoproj.io/orders.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/zeus-repo
spec:
  project: staging-orders-apps
  source:
    repoURL: https://github.com/basebandit/infrastructure-zeus.git
    targetRevision: main
    path: charts/orders
    helm:
      valueFiles:
        - staging-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: orders
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: staging-orders-apps
  namespace: argocd
spec:
  description: Staging Orders Service Applications
  sourceRepos:
    - '*'
  destinations:
    - namespace: orders
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
