apiVersion: v1
kind: Secret
metadata:
  name: zeus-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:basebandit/zeus.git"
  sshPrivateKey: |
  "...""
  insecure: "false"
  enableLfs: "true"