apiVersion: v1
kind: Secret
metadata:
  name: zeus-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: "git@github.com:basebandit/zeus.git"
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACAnual3OXmSVWlAQEH/EGLLye/laDC1Qw9Rnx+LAWwHSQAAAKBGIqLFRiKi
    xQAAAAtzc2gtZWQyNTUxOQAAACAnual3OXmSVWlAQEH/EGLLye/laDC1Qw9Rnx+LAWwHSQ
    AAAEANJvoRAkNW0oqu/MGPUNZL4XYRi3O5Lbsh98KlGNrR3Se5qXc5eZJVaUBAQf8QYsvJ
    7+VoMLVDD1GfH4sBbAdJAAAAGWV2YW5zb25td2FuZ2k4M0BnbWFpbC5jb20BAgME
    -----END OPENSSH PRIVATE KEY-----
  enableLfs: "true"
  insecure: "false"