apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secret
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: argocd
    kind: SecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: argocd-secret
    template:
      metadata:
        labels:
          app.kubernetes.io/name: argocd-secret
          app.kubernetes.io/part-of: argocd
  data:
  - secretKey: admin.password
    remoteRef:
      key: /infra/argo/staging-basebandit-eks-cluster/argocd-admin-password
  - secretKey: admin.passwordMtime
    remoteRef:
      key: /infra/argo/staging-basebandit-eks-cluster/argocd-admin-password-mtime
  - secretKey: server.secretkey
    remoteRef:
      key: /infra/argo/staging-basebandit-eks-cluster/argocd-server-secret-key